repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: llmstudio/
        exclude: ^llmstudio/ui/
      - id: end-of-file-fixer
        files: llmstudio/
        exclude: ^llmstudio/ui/
      - id: check-yaml
        files: llmstudio/
        exclude: ^llmstudio/ui/
      - id: check-added-large-files
        files: llmstudio/
        exclude: ^llmstudio/ui/
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        files: llmstudio/
        exclude: ^llmstudio/ui/
        args:
          - "--line-length=99"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: llmstudio/
        exclude: ^llmstudio/ui/
        args:
          - "--line-length=99"
          - "--profile=black"
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: ^llmstudio/ui/|__init__.py$
        files: llmstudio/
        args:
          [
            --remove-all-unused-imports,
            --recursive,
            --remove-unused-variables,
            --in-place,
          ]
        additional_dependencies: [flake8]
